Fixed error
System.Text.Json.JsonException: A possible object cycle was detected which is not supported. This can either be due to a cycle or if the object
depth is larger than the maximum allowed depth of 32